---
title: About
date: 2025-01-31T14:46:40-04:00
meta: false
draft: false
--- 

* Who are we?
The StuyCS Family is a community comprised of people affiliated with
The Stuyvesant High School Computer Science program. This includes
Stuyvesant Alums who have taken the CS courses offered at Stuyvesant
as well as Stuyvesant Alums who found there way to tech later in life
as well as other affiliates. 

* Our Goals:

We hope to foster a supportive community among StuyCS Family
members. As such, members of this community are encouraged to share
and discuss items of interest. Items discussed can be anything that
the community finds value in. This could include professional
opportunities, recreational opportunities, or any other items of
interest.

Members are encouraged to post items of interest to our mailing
list. Members who can provide expertise with regards to any post are
expected to contribute to the discussion.

We also hope to foster in person events where community members can
meet and get to know each other.

* Code of Conduct:


