---
title: About
date: 2025-01-31T14:46:40-04:00
meta: false
draft: false
--- 

* Who are we?
The StuyCS Family is a community comprised of people affiliated with
The Stuyvesant High School Computer Science program. This includes
Stuyvesant Alums who have taken the CS courses offered at Stuyvesant
as well as Stuyvesant Alums who found their way to tech later in life
as well as other affiliates. 

* Our Goals:

We hope to foster a supportive community among StuyCS Family
members. As such, members of this community are encouraged to share
and discuss items of interest. Items discussed can be anything that
the community finds value in. This could include professional
opportunities, recreational opportunities, or any other items of
interest.

Members are encouraged to post items of interest to our mailing
list. Members who can provide expertise with regards to any post are
expected to contribute to the discussion.

We also hope to foster in person events where community members can
meet and get to know each other.

* Code of Conduct:
- This forum is for general discussion and is not limited to tech or
  job related topics.
- be respectful of other members of this community. This means please
  use etiquette and politeness. 
- refrain from using the board to send abusive or harassing private
  messages or emails.
- remember that these forums are read by people of all background so
  please strive to maintain postings appropriate to everyone.
- if you have found a post that you feel is inappropriate or that
  violates the forum Code of Conduct please report it by emailing [[mailto:elders@stuycs.org][elders@stuycs.org]].
- understand that all posts made to these forums express the views and
  opinions of the author.
- agree not to post any abusive, obscene, vulgar, slanderous, hateful,
  threatening material or any other material that may violate any
  applicable laws.
